
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TRANSICIONES = 15;
  public static final int DESC = 17;
  public static final int CADENA = 2;
  public static final int DOLAR = 28;
  public static final int OR = 24;
  public static final int IGUAL = 18;
  public static final int AP_INI = 7;
  public static final int T = 11;
  public static final int AFD_FIN = 6;
  public static final int FLECHA = 23;
  public static final int P = 12;
  public static final int N = 10;
  public static final int DOS_PUNTOS = 26;
  public static final int I = 13;
  public static final int PAREN_IZQ = 21;
  public static final int CARACTER = 4;
  public static final int VER_AUTOMATAS = 16;
  public static final int COMA = 27;
  public static final int PAREN_DER = 22;
  public static final int NOMBRE = 9;
  public static final int EOF = 0;
  public static final int A = 14;
  public static final int error = 1;
  public static final int AFD_INI = 5;
  public static final int AP_FIN = 8;
  public static final int IDENTIFICADOR = 3;
  public static final int LLAVE_IZQ = 19;
  public static final int PUNTO_COMA = 25;
  public static final int LLAVE_DER = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "IDENTIFICADOR",
  "CARACTER",
  "AFD_INI",
  "AFD_FIN",
  "AP_INI",
  "AP_FIN",
  "NOMBRE",
  "N",
  "T",
  "P",
  "I",
  "A",
  "TRANSICIONES",
  "VER_AUTOMATAS",
  "DESC",
  "IGUAL",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "PAREN_IZQ",
  "PAREN_DER",
  "FLECHA",
  "OR",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "COMA",
  "DOLAR"
  };
}

